### ISSUE TITLE
Does This Only Work With #![feature(async_closure)]?

### ISSUE THREAD

**Issue by zicklag** [w3reality/wasm-mt#2]
Is it possible to use `wasm-mt` without requring the nightly feature flag?

**Comment by j-devel** [comment]
Unfortunately not for now.  Aside from the `async_closure ` nightly feature, `wasm-mt` fundamentally depends on the `serde_traitobject` crate that [requires Rust nightly](https://github.com/alecmocatta/serde_traitobject#note).

**Comment by zicklag** [comment]
Ah, OK. Thanks :slightly_smiling_face: :+1:
