### ISSUE TITLE
[question] Technically is it Thread or Process ?

### ISSUE THREAD

**Issue by michael8090** [w3reality/wasm-mt#5]
It seems the library is for multithreading, but it uses web workers with isolated memories, which seem more like processes as they surely doesn't share the  same memory address with the main thread.

**Comment by j-devel** [comment]
Here, we are using the term "thread" meaning "worker thread" explained in https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API

Regarding shared memory, as noted in [README](https://github.com/w3reality/wasm-mt#background-and-implementation), this crate is a multi-"thread" solution that does not require [`SharedArrayBuffer`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer).  But technically, I think it *could* be extended to have the opt-in `SharedArrayBuffer` support.
