### ISSUE TITLE
Failed on running examples

### ISSUE THREAD

**Issue by PooyaEimandar** [w3reality/wasm-mt#6]
[start-app](https://github.com/w3reality/wasm-mt/blob/master/examples/deps/start-app.js) thrown an exception:

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'src')
    at eval (eval at default (start-app.js:6:19), <anonymous>:10:53)
    at eval (eval at default (start-app.js:6:19), <anonymous>:675:3)
    at default (start-app.js:8:17)
```

**Comment by j-devel** [comment]
Thanks for reporting this!  Now fixed.

The latest wasm-bindgen seems to generate 'pkg/*.js' artifact that initializes `script_src` at the top of the function:
https://github.com/w3reality/wasm-mt/blob/f4314aaceaa05dca3566c3aaaa1fecba6ea9c009/examples/exec/pkg/exec.js#L1-L9

Actually, we wasm-mt does not rely on this `script_src` variable, so  workaround is applied to 'start-app.js' d38b224
